package leetcode;

/**
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
public class FindtheDifference {
    public char findTheDifference(String s, String t) {
        int[] sumA = new int[26];
        for (int i = 0; i < s.length(); i++) {
            sumA[s.charAt(i) - 'a']++;
        }
        for (int i = 0; i < t.length(); i++) {
            sumA[t.charAt(i) - 'a']--;
        }
        char result = 'a';
        for (int i = 0; i < sumA.length; i++) {
            if (sumA[i] != 0) {
                result = (char)('a' + i);
                break;
            }
        }
        return result;

    }
}
